[package]
name = "btree-rewrite"
version = "0.1.0"
authors = ["Jonathan S <gereeter+code@gmail.com>"]

[dev-dependencies]
rand = "*"

[dev-dependencies.btree]
git = "http://github.com/apasel422/btree.git"
